printf("<html>\n");
printf("      <head>\n");
printf("            <title>\n");
printf("                  Sistema de gerenciamento de contas\n");
printf("                  <meta autores = "David Vinicius Ferreira Moreira e Ewerton Vieira de Silles">\n");
printf("            </title>\n");
printf("      </head>\n");
printf("      <body bgcolor = "cyan">\n");
printf("\n");
printf("            <div align = "center">\n");
printf("                  <font size="15">\n");
printf("                  Sistema de gerenciamento de contas\n");
printf("                  </font>\n");
printf("                  <br><br>\n");
printf("                  <font size="-10">\n");
printf("                        autores: <br>\n");
printf("                        <a href="mailto:davidmoreira@poli.ufrj.br">David Vinicius Ferreira Moreira</a> <br>\n");
printf("                        <a href="mailto:ewerton5@poli.ufrj.br">Ewerton Vieira de Silles</a>\n");
printf("                  </font>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("            </div>\n");
printf("\n");
printf("            <div align = "center">\n");
printf("                  <form action="dvfmEvsUmlRequestRegistration.cgi" method="post">\n");
printf("                        <table border="0">\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Correio eletronico para solicitaçao:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type="text" name="dvfmEvsUmlAdimim" max="1024"> \n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Nome completo:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type="text" name="dvfmEvsUmlUserName" max="256">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Confirmar nome completo:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type="text" name="dvfmEvsUmlUserNameConfirmation" max="256">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Correio eletronico:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type="text" name="dvfmEvsUmlEmail" max="1024">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Confirmar Correio eletronico:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type="text" name="dvfmEvsUmlEmailConfirmation" max="1024">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type="submit" value="Registar -se">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td colspan="2">\n");
printf("                                          <input type="hidden" name="dvfmEvsUmlConfigurationFileName">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td colspan="2">\n");
printf("                                          <input type="hidden" name="dvfmEvsUmlLanguage">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                        </table>\n");
printf("                  </form>\n");
printf("            </div>\n");
printf("\n");
printf("            <div align = "center">\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <pre>\n");
printf("                        <a href="dvfmEvsUmlMain.cgi?dvfmEvsUmlConfigurationFileName=dvfmEvs-uml.cfg&dvfmEvsUmlLanguage=dvfmEvsUmlEnglish">Pagina inicial</a>\n");
printf("                  </pre>\n");
printf("            </div>\n");
printf("      </body>\n");
printf("</html>\n");
