printf("<html>\n");
printf("      <head>\n");
printf("            <meta autores = \"David Vinicius Ferreira Moreira e Ewerton Vieira de Silles\">\n");
printf("            <title>\n");
printf("                  Sistema de gerenciamento de contas\n");
printf("            </title>\n");
printf("	      <style type=\"text/css\">\n");
printf("                  body {\n");
printf("                        text-align: center;\n");
printf("                        font-family: Arial, sans-serif;\n");
printf("                        background-color: #dddddd;\n");
printf("                        color: rgba(0,0,0,1);\n");
printf("                  }\n");
printf("                  div {\n");
printf("                        width: 900px;\n");
printf("                        background-color: white;\n");
printf("                        margin: 0px auto 0px auto;\n");
printf("                        box-shadow: 0px 0px 10px rgba(0,0,0,.5);\n");
printf("                        padding: 10px;\n");
printf("                  }\n");
printf("                  p {\n");
printf("                        font-size: 8pt;\n");
printf("                  }\n");
printf("                  a {\n");
printf("                        color: #606060;\n");
printf("                        text-decoration: none;\n");
printf("                  }\n");
printf("                  h1 {\n");
printf("                        font-family: 'FonteLogo', sans-serif;\n");
printf("                        font-size: 30pt;\n");
printf("                        color: #606060;\n");
printf("                        text-shadow: 1px 1px 1px rgba(0,0,0,.6);\n");
printf("                        padding: 0px;\n");
printf("                        margin-bottom: 0px;\n");
printf("                  }\n");
printf("                  h2 {\n");
printf("                        font-family: 'Titillium Web', sans-serif;\n");
printf("                        font-size: 15pt;\n");
printf("                        color: #888888;\n");
printf("                        padding: 0px;\n");
printf("                        margin-top: 0px;\n");
printf("                  }\n");
printf("                  a:hover {\n");
printf("                        text-decoration: underline;\n");
printf("                  }\n");
printf("                  header {\n");
printf("                        border-bottom: 1px #606060 solid;\n");
printf("                        height: 150px;\n");
printf("                        margin-bottom: 10px;\n");
printf("                  }\n");
printf("                  table {\n");
printf("                        margin-left: auto;\n");
printf("                        margin-right: auto;\n");
printf("                  }\n");
printf("                  table td {\n");
printf("                        padding: 10px;\n");
printf("                  }\n");
printf("                  footer {\n");
printf("                        clear: both;\n");
printf("                        border-top: 1px solid #606060;\n");
printf("                        margin-top: 10px;\n");
printf("                        padding-top: 20px;\n");
printf("                  }\n");
printf("            </style>\n");
printf("      </head>\n");
printf("      <body>\n");
printf("            <header>\n");
printf("                  <h1>\n");
printf("                  Sistema de gerenciamento de contas\n");
printf("                  </h1>\n");
printf("                        <p>autores:</p> \n");
printf("                        <p><a href=\"mailto:davidmoreira@poli.ufrj.br\">David Vinicius Ferreira Moreira</a></p>\n");
printf("                        <p><a href=\"mailto:ewerton5@poli.ufrj.br\">Ewerton Vieira de Silles</a></p>\n");
printf("            </header>\n");
printf("            <div>\n");
printf("                  <h2>\n");
printf("                  Cadastro\n");
printf("                  </h2>\n");
printf("                  <form action=\"dvfmEvsUmlRequestRegistration.cgi\" method=\"post\">\n");
printf("                        <table>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Correio eletronico para solicitaçao:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"text\" name=\"dvfmEvsUmlAdimim\" max=\"1024\"> \n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Nome completo:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"text\" name=\"dvfmEvsUmlUserName\" max=\"256\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Confirmar nome completo:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"text\" name=\"dvfmEvsUmlUserNameConfirmation\" max=\"256\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Correio eletronico:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"text\" name=\"dvfmEvsUmlEmail\" max=\"1024\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          Confirmar Correio eletronico:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"text\" name=\"dvfmEvsUmlEmailConfirmation\" max=\"1024\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"submit\" value=\"Registar -se\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td colspan=\"2\">\n");
printf("                                          <input type=\"hidden\" name=\"dvfmEvsUmlConfigurationFileName\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td colspan=\"2\">\n");
printf("                                          <input type=\"hidden\" name=\"dvfmEvsUmlLanguage\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                        </table>\n");
printf("                  </form>\n");
printf("            </div>\n");
printf("            <footer>\n");
printf("                  <pre>\n");
printf("                        <a href=\"dvfmEvsUmlMain.cgi?dvfmEvsUmlConfigurationFileName=dvfmEvs-uml.cfg&dvfmEvsUmlLanguage=dvfmEvsUmlEnglish\">Pagina inicial</a>\n");
printf("                  </pre>\n");
printf("            </footer>\n");
printf("      </body>\n");
printf("</html>\n");
