printf("<html>\n");
printf("      <head>\n");
printf("            <title>\n");
printf("                  Sistema de gerenciamento de contas\n");
printf("                  <meta autores = \"David Vinicius Ferreira Moreira e Ewerton Vieira de Silles\">\n");
printf("            </title>\n");
printf("            <style type=\"text/css\">\n");
printf("                  body {\n");
printf("                        font-family: Arial, sans-serif;\n");
printf("                        background-color: #dddddd;\n");
printf("                        color: rgba(0,0,0,1);\n");
printf("                  }\n");
printf("                  div {\n");
printf("                        width: 900px;\n");
printf("                        background-color: white;\n");
printf("                        margin: 0px auto 0px auto;\n");
printf("                        box-shadow: 0px 0px 10px rgba(0,0,0,.5);\n");
printf("                        padding: 10px;\n");
printf("                  }\n");
printf("                  p {\n");
printf("                        text-align: justify;\n");
printf("                        text-indent: 50px;\n");
printf("                  }\n");
printf("                  a {\n");
printf("                        color: #606060;\n");
printf("                        text-decoration: none;\n");
printf("                  }\n");
printf("                  a:hover {\n");
printf("                        text-decoration: underline;\n");
printf("                  }\n");
printf("                  header {\n");
printf("                        border-bottom: 1px #606060 solid;\n");
printf("                        height: 150px;\n");
printf("                  }\n");
printf("                  header h1 {\n");
printf("                        font-family: 'FonteLogo', sans-serif;\n");
printf("                        font-size: 30pt;\n");
printf("                        color: #606060;\n");
printf("                        text-shadow: 1px 1px 1px rgba(0,0,0,.6);\n");
printf("                        padding: 0px;\n");
printf("                        margin-bottom: 0px;\n");
printf("                  }\n");
printf("                  table {\n");
printf("                        margin-left: auto;\n");
printf("                        margin-right: auto;\n");
printf("                  }\n");
printf("                  table td {\n");
printf("                        padding: 10px;\n");
printf("                  }\n");
printf("                  footer {\n");
printf("                        clear: both;\n");
printf("                        border-top: 1px solid #606060;\n");
printf("                  }\n");
printf("                  footer p {\n");
printf("                        text-align: center;\n");
printf("                  }\n");
printf("            </style>\n");
printf("      </head>\n");
printf("      <body bgcolor = \"cyan\">\n");
printf("\n");
printf("            <header align = \"center\">\n");
printf("                  <h1>\n");
printf("                  Sistema de gerenciamento de contas\n");
printf("                  </h1>\n");
printf("                  <br><br>\n");
printf("                  <font size="-10">\n");
printf("                        autores: <br>\n");
printf("                        <a href=\"mailto:davidmoreira@poli.ufrj.br\">David Vinicius Ferreira Moreira</a> <br>\n");
printf("                        <a href=\"mailto:ewerton5@poli.ufrj.br\">Ewerton Vieira de Silles</a>\n");
printf("                  </font>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("            </header>\n");
printf("\n");
printf("            <div>\n");
printf("                  <form action=\"dvfmEvsUmlLogin.cgi\" method=\"post\">\n");
printf("                        <table border="0">\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          login:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"text\" name=\"dvfmEvsUmlNickname\" max=\"127\"> \n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("                                          senha:\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"password\" name=\"dvfmEvsUmlPassword\" max=\"65\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td>\n");
printf("\n");
printf("                                    </td>\n");
printf("                                    <td>\n");
printf("                                          <input type=\"submit\" value=\"Entrar\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td colspan="2">\n");
printf("                                          <input type=\"hidden\" name=\"dvfmEvsUmlConfigurationFileName\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                              <tr>\n");
printf("                                    <td colspan="2">\n");
printf("                                          <input type=\"hidden\" name=\"dvfmEvsUmlLanguage\">\n");
printf("                                    </td>\n");
printf("                              </tr>\n");
printf("                        </table>\n");
printf("                  </form>\n");
printf("            </div>\n");
printf("\n");
printf("            <footer align = \"center\">\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <br>\n");
printf("                  <pre>\n");
printf("                        <p></p><a href=\"dvfmEvsUmlMain.cgi?dvfmEvsUmlConfigurationFileName=dvfmEvs-uml.cfg&dvfmEvsUmlLanguage=dvfmEvsUmlEnglish\">ingl&ecirc;s</a>      <a href=\"dvfmEvsUmlShowRequestRegistrationForm.cgi?dvfmEvsUmlConfigurationFileName=dvfmEvs-uml.cfg&dvfmEvsUmlLanguage=dvfmEvsUmlPortuguese\">cadastre -se</a>      <a href=\"dvfmEvsUmlShowRequestPasswordResetForm.cgi\">senha temporaria</a>      <a href=\"dvfmEvsUmlShowWebHelp.cgi\">ajuda</a>      <a href=\"dvfmEvsUmlShowLicense.cgi\">lic\n");
printf("n&ccedil;a de uso</a></p>       \n");
printf("                  </pre>\n");
printf("            </footer>\n");
printf("      </body>\n");
printf("</html>\n");
